### ISSUE TITLE
请问RetinaDetector与YOLO4, YOLO5相比，效果如何？

### ISSUE THREAD

**Issue by pustar** [bleakie/RetinaDetector#11]
冒昧请教下，RetinaDetector与YOLO4, YOLO5相比，效果如何？在COCO上的表现如何？对小目标的检测效果相比如何？有什么优势和不足？

**Comment by bleakie** [comment]
retinaface的好处是对硬件的性能要求不高，效果不如yolo4+，小目标检测上个人感觉yolo4+已经很优秀了
