### ISSUE TITLE
False Face Predictions?

### ISSUE THREAD

**Issue by PhenomenalOnee** [bleakie/RetinaDetector#5]
I run your test.py file with your given face model
It is predicting too much false faces
Detecting blur faces too
![12](https://user-images.githubusercontent.com/47495143/73717217-26577900-473f-11ea-8dc0-a886ff0ec825.jpg)

![10](https://user-images.githubusercontent.com/47495143/73717189-1475d600-473f-11ea-8f3d-61933993a524.jpg)
![19](https://user-images.githubusercontent.com/47495143/73717190-1475d600-473f-11ea-92a3-fb0ce982085b.jpg)
![28](https://user-images.githubusercontent.com/47495143/73717192-1475d600-473f-11ea-94b6-7b489a6d2b8a.jpg)

**Comment by bleakie** [comment]
face model is based on mobilenet, so not as good as resnet50
