### ISSUE TITLE
关于比原版误检更低

### ISSUE THREAD

**Issue by Wblossom** [bleakie/RetinaDetector#8]
@bleakie Hi，想问下你主要改进了什么使得RetinaDetector比原版误检更低？角度较大和模糊超过0.6的face自动忽略？无效人脸过滤？

**Comment by bleakie** [comment]
在数据预处理阶段改进了读取方法，[https://github.com/bleakie/RetinaDetector/blob/ffa3592613ab4fe120b598a64ce2a5106e7c9e43/rcnn/dataset/retinaface.py#L95](url)

**Comment by Wblossom** [comment]
@bleakie  谢谢~可以再大概说说改进读取方法的大概内容嘛

**Comment by Wblossom** [comment]
@bleakie 谢谢~可以再大概说说改进读取方法的大概内容嘛


| |
w1947566166
|
|
w1947566166@163.com
|
签名由网易邮箱大师定制
在2020年11月13日 11:01，bleakie<notifications@github.com> 写道：

在数据预处理阶段改进了读取方法，https://github.com/bleakie/RetinaDetector/blob/ffa3592613ab4fe120b598a64ce2a5106e7c9e43/rcnn/dataset/retinaface.py#L95

**Comment by bleakie** [comment]
详见code
