### ISSUE TITLE
请问能识别4~10个像素大小的目标吗？

### ISSUE THREAD

**Issue by pustar** [bleakie/RetinaDetector#9]
小白问个问题，请问config.TRAIN.MIN_BOX_SIZE = 10 #最小bbox，是指框的最短边长度吗？还是就是指bbox的面积是10？能识别4~10个像素大小的目标吗？

**Comment by bleakie** [comment]
1.最短边bbox
2.想识别更小像素可以把这个值设小（小于10识别性能会差很多）
